name: ğŸ“¦ Release
run-name: ğŸ“¦ Release - ${{ inputs.tag-name || github.sha || github.ref }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: Tag name
        required: false
        type: string
      skip-npm:
        description: Skip npm publish
        required: false
        type: boolean

permissions:
  contents: write

jobs:
  release:
    name: ğŸ“¦ Tag and release commit
    runs-on: ubuntu-latest

    outputs:
      tag-name: ${{ steps.push-tag.outputs.tag_name }}
      commit-hash: ${{ steps.push-tag.outputs.commit_hash }}

    steps:
      - name: â›™ Checkout branch ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.CI_TOKEN }}

      - name: ğŸ§± Install
        uses: ./.github/actions/install

      - name: ğŸ·ï¸ Release
        run: |
          # =================  ğŸ·ï¸ Release =================

          # setup git credentials
          git config user.name "GitHub Release Bot"
          git config user.email "<>"

          # generate release
          pnpm run release

      - name: â›™ Push to remote
        id: push-tag
        run: |
          # ================= â›™ Remote =================

          # Check status
          git status
          git diff --color -U0 | cat

          # push changes
          git push origin --follow-tags

          tag_name=$(git describe --abbrev=0 --match 'v*')
          commit_hash=$(git rev-parse HEAD)

          echo "Pushing tag: ${tag_name}"
          echo "Pushing commit: ${commit_hash}"

          echo "tag_name=${tag_name}" >> "$GITHUB_OUTPUT"
          echo "commit_hash=${commit_hash}" >> "$GITHUB_OUTPUT"

      - name: ğŸ·ï¸ Generate Release changelog
        run: |
          # =================  ğŸ·ï¸ Changelog  =================

          pnpm run release:changelog

      - name: ğŸ“¦ Push Release to github
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag-name || steps.push-tag.outputs.tag_name }}
          body_path: RELEASE.md

  publish:
    name: â˜ï¸ Publish
    needs: release
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      tag-name: ${{ inputs.tag-name || needs.release.outputs.tag-name }}
